[
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
     "question": "The retail disc of Tony Hawk&#039;s Pro Skater 5 only comes with the tutorial.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "medium",
     "question": "Sargon II, a king of the Neo-Assyrian Empire, was a direct descendant of Sargon of Akkad.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Politics", "type": "boolean", "difficulty": "easy",
     "question": "In 2016, the United Kingdom voted to stay in the EU.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
     "difficulty": "medium",
     "question": "The animated film &quot;Spirited Away&quot; won the Academy Award for Best Animated Feature at the 75th Academy Awards in 2003.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
     "question": "&quot;Number 16 Bus Shelter&quot; was a child&#039;s name that was approved by the New Zealand government.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "In Alfred Hitchcock&#039;s film &#039;Psycho&#039; it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
     "question": "In the TV series Red Dwarf, Kryten&#039;s full name is Kryten 2X4B-523P.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium",
     "question": "Antarctica is the largest desert in the world.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "&quot;The Division Bell&quot; is the final album of the progressive rock band Pink Floyd.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "question": "In the periodic table, Potassium&#039;s symbol is the letter K.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Politics", "type": "boolean", "difficulty": "hard",
     "question": "George Clinton, Vice President of the United States (1805-1812), is an ancestor of President Bill Clinton.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The game &quot;Pocket Morty&quot; has a Morty called &quot;Pocket Mortys Morty&quot;?",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
     "question": "In &quot;Star Trek: The Next Generation&quot;, Data is the only android in existence.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
     "question": "&quot;The Simpsons&quot; family is named after creator Matt Groening&#039;s real family.",
     "correct_answer": "True", "incorrect_answers": ["False"]}]}
